### ISSUE TITLE
Depth not working on Neumorphic Button Widget

### ISSUE THREAD

**Issue by Rishabh-More** [Idean/Flutter-Neumorphic#212]
Issue: **Depth parameter is not working on Neumorphic Button Widget.**

Dart SDK version: 2.12.0
Flutter SDK version: 2.0.0 stable channel
Library version: 3.1.0

The depth property is working completely fine for other widgets but not with Neumorphic Button. Here's the screenshot of the app:

![Screenshot_20210315-145547](https://user-images.githubusercontent.com/43803144/111133184-3c6d7500-85a0-11eb-9af6-7005ca8f4f48.jpg)

Here's the code of my `main.dart` file:
```
import 'package:flutter_neumorphic/flutter_neumorphic.dart';

void main() {
  runApp(NeumorphicApplication());
}

class NeumorphicApplication extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return NeumorphicApp(
      debugShowCheckedModeBanner: false,
      title: 'Neumorphic Playground',
      themeMode: ThemeMode.system,
      theme: NeumorphicThemeData(
        baseColor: Color(0xFFF2F2F2),
        lightSource: LightSource.topLeft,
        depth: 5.0
      ),
      darkTheme: NeumorphicThemeData(
        baseColor: Color(0xFF2E3237),
        lightSource: LightSource.topLeft,
        depth: 5.0
      ),
      home: NeuHomePage(),
    );
  }
}

class NeuHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: NeumorphicAppBar(
        title: Text('Neumorhpic Playground')
      ),
      backgroundColor: NeumorphicTheme.baseColor(context),
      body: Center(
        child: Column(
          children: [
            Neumorphic(
              style: NeumorphicStyle(
                depth: 10,
                shape: NeumorphicShape.flat,
                lightSource: LightSource.topLeft,
                border: NeumorphicBorder(width: 0.5),
                boxShape: NeumorphicBoxShape.roundRect(BorderRadius.circular(25)),
              ),
              margin: EdgeInsets.all(25),
              child: Center(
                child: Container(
                  child: Text('This is something'),
                  margin: EdgeInsets.all(125),
                ),
              )
            ),
            NeumorphicButton(
              minDistance: -5.0,
              style: NeumorphicStyle(
                depth: 20,
                shape: NeumorphicShape.flat,
                lightSource: LightSource.topLeft,
                border: NeumorphicBorder(width: 0.5),
                boxShape: NeumorphicBoxShape.roundRect(BorderRadius.all(Radius.circular(25))),
              ),
              margin: EdgeInsets.all(10),
              padding: EdgeInsets.all(18.0),
              child: Container(
                child: Icon(Icons.play_arrow),
                margin: EdgeInsets.all(15),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

Here's my `pubspec.yaml` file as well: 

```
name: neumorphic_playground
description: A Flutter app to play with some Neumorphic Libraries

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_neumorphic: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
