### ISSUE TITLE
ThemeData accentColor deprecated in Flutter 3.10.0

### ISSUE THREAD

**Issue by gmckesey** [Idean/Flutter-Neumorphic#274]
Projects including flutter_neomorphic will not build as of Flutter 3.10.0 due to the accentColor parameter in the ThemeData constructor being deprecated.  The line at issue is app.dart:89.

**Comment by noahvelasco** [comment]
To temporarily solve this issue run in your project directory -

"flutter downgrade"

then accept the changes. You might have a few issues (const keywords, or others) but they are solvable by you and not the package. This should suffice until they fix this issue.

**Comment by den0206** [comment]
temporary fix was sent out to [PR](https://github.com/Idean/Flutter-Neumorphic/pull/276).
```
  flutter_neumorphic: 
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
```
